// <auto-generated />
// Tool strings for MCP tools — extracted from ToolStrings.resx
// This file is the SSOT for all MCP-facing English strings.
//

using System.Globalization;

namespace DotNetAnalyzer.Resources;

/// <summary>
/// Resource strings for MCP tools. All MCP-facing output uses these constants/methods.
/// Entries are managed in ToolStrings.resx and extracted here for compile-time use.
/// </summary>
public static partial class ToolStrings
{
    #region Attribute strings (compile-time constants)

    public const string AnalyzeCode = "Analyze syntax and semantic structure of code, including syntax tree, type info, namespaces, classes, and methods";

    public const string GetTestCoverage = "Get project test coverage info; uses coverage.cobertura.xml real data when available, falls back to heuristic estimation";

    public const string FindDeadCode = "Find unused code";

    public const string AnalyzePerformance = "Analyze performance bottlenecks";

    public const string GenerateDocumentation = "Generate project documentation from XML doc comments";

    public const string ListProjects = "List all projects in the solution, including dependency analysis";

    public const string GetProjectInfo = "Get detailed project information";

    public const string AnalyzeDependencies = "Analyze project dependencies, including project references, package dependencies, transitive dependencies, and circular dependency detection";

    public const string GetSolutionInfo = "Get detailed solution information, including build order and startup projects";

    public const string GetDiagnostics = "Get C# compiler diagnostics (errors, warnings, info)";

    public const string FindReferences = "Find all reference locations of a symbol, including cross-file references";

    public const string FindDeclarations = "Find declaration locations of a symbol, including base class members and interface members";

    public const string GetSymbolInfo = "Get detailed symbol information, including type, modifiers, and parameters";

    public const string GoToDefinition = "Navigate to the definition of the symbol at the specified position";

    public const string GetTypeHierarchy = "Get the type inheritance hierarchy, including base types, derived types, and implemented interfaces";

    public const string GetMemberHierarchy = "Get the member override and implementation hierarchy";

    public const string GetSemanticModel = "Get semantic model information at the specified position, including symbol, type, and constant values";

    public const string GetSyntaxTree = "Get the syntax tree structure of a file";

    public const string GetCodeMetrics = "Get code metrics including cyclomatic complexity, maintainability index, etc.";

    public const string ExtractMethod = "Extract selected code into a new method";

    public const string RenameSymbol = "Rename a symbol (type, method, field, etc.) and update all references";

    public const string IntroduceVariable = "Extract an expression into a local variable";

    public const string ListRefactorers = "List all available refactorers";

    public const string GenerateInterfaceImpl = "Generate interface implementation for a class";

    public const string GenerateConstructor = "Generate constructor for a class";

    public const string RemoveUnusedUsings = "Remove unused using directives";

    public const string SortUsings = "Sort using directives";

    public const string AddMissingImports = "Add missing using directives";

    public const string GetCallerInfo = "Get all locations that call the specified method, including callers, call types, and call context";

    public const string GetCalleeInfo = "Get all methods called within a method, supporting cross-document resolution, interface/virtual dispatch, and cycle detection";

    public const string GetCallGraph = "Generate a complete call graph with nodes, edges, and metrics; supports multiple visualization formats (dot, svg, json, mermaid)";

    public const string CompareSyntaxTrees = "Compare syntax tree differences between two files, returning a structured diff list and statistics";

    public const string GetCodeDiff = "Generate code diff between two files in unified diff format with statistics";

    public const string ApplyCodeChange = "Apply code changes to a file, optionally format the result, and return modified content with diagnostics";

    public const string GetCodeActions = "Get available code actions at the specified position, including refactorings, fixes, and generations";

    public const string GetRefactorings = "Get available refactorings at the specified position, including preview and applicability checks";

    public const string GetCompletionList = "Get code completion suggestions at the specified position";

    public const string ResolveSymbol = "Resolve the symbol at the specified position, supporting alias resolution and override resolution";

    public const string GetDefinitionAndReferences = "Get the symbol definition and all references in one call, including hierarchy";

    public const string GetDocumentList = "Get all document files in a project, including line counts and error status";

    public const string DetectCodeSmells = "Detect code smells in the project";

    public const string QuantifyTechnicalDebt = "Quantify the project's technical debt";

    public const string GenerateQualityReport = "Generate a comprehensive quality report for the project";

    public const string StartFileWatching = "Start file watching for incremental analysis";

    public const string StopFileWatching = "Stop file watching";

    public const string AnalyzeChangeImpact = "Analyze the impact scope of code changes (heuristic results)";

    public const string GetCacheStatistics = "Get analysis cache statistics";

    public const string ClearCache = "Clear analysis cache";

    public const string GenerateDependencyGraph = "Generate a dependency graph";

    public const string GenerateHeatmap = "Generate an architecture heatmap";

    public const string CheckArchitectureRules = "Check project architecture rule compliance, reading rule configuration from dotnet-analyzer.rules.json in the project directory";

    public const string EvaluateArchitecture = "Evaluate project architecture compliance using a custom rule file; supports specifying an external rule file path";

    public const string GenerateArchitectureSarif = "Generate architecture check SARIF v2.1.0 report for integration with GitHub Code Scanning and other platforms";

    public const string DecompileAssembly = "Decompile a .NET assembly (DLL/EXE) into readable C# source code. Optional typeName parameter limits decompilation to a specific type.";

    public const string AnalyzeIL = "Analyze IL bytecode of a .NET assembly, detecting boxing/unboxing, virtual calls, exception handling, and other performance characteristics. Optional typeName limits analysis to a specific type.";

    public const string GetAssemblyMetadata = "Read .NET assembly metadata, including name, version, target framework, assembly references, and type statistics";

    public const string GetApiSurface = "Extract the API surface of a .NET assembly, including public/internal types and their members. Optional accessibility filter (Public, Internal, Protected, Private).";

    public const string ScanSecurityVulnerabilities = "Scan project for security vulnerabilities (hardcoded credentials, SQL injection, command injection, unsafe deserialization, path traversal, XSS)";

    public const string GenerateSecuritySarif = "Generate security vulnerability SARIF v2.1.0 format report";

    public const string GetSecurityRules = "Get all registered security detection rules (SEC001-SEC006)";

    public const string CheckLicenseCompliance = "Check license compliance of project dependencies";

    public const string ScanNuGetVulnerabilities = "Scan project NuGet dependencies for known vulnerabilities";

    public const string ScanDependenciesHealth = "Scan project dependency health (outdated packages, deprecated packages, vulnerabilities, license compliance)";

    public const string DetectDependencyConflicts = "Detect version conflicts where multiple projects in the solution use different versions of the same package";

    public const string AnalyzeSolutionPerformance = "Analyze solution performance metrics (project count, document count, lines of code, cache hit rate, optimization recommendations)";

    public const string OptimizeWorkspaceCache = "Optimize workspace cache, releasing unnecessary cached entries";

    public const string GetWorkspaceStats = "Get workspace runtime statistics (cache capacity, usage, hit rate, etc.)";

    public const string AnalyzeXaml = "Parse XAML file into a structured model, extracting element tree, namespaces, Binding expressions, and resource references";

    public const string ValidateBindings = "Validate Binding expressions in a XAML file, checking whether paths correspond to valid properties on the ViewModel";

    public const string AnalyzeXamlResources = "Analyze XAML ResourceDictionary in the project, tracking resource definitions, references, and merge relationships; detect missing resources and duplicate keys";

    public const string MapViewViewModel = "Scan all XAML and C# files in the project to establish View-ViewModel mapping relationships";

    public const string DetectMvvmViolations = "Detect MVVM pattern violations in the project (code-behind business logic, ViewModel referencing UI namespaces, Command not implementing ICommand)";

    public const string DetectAsyncAntipatterns = "Detect async anti-patterns in the project (async void, .Result/.Wait() deadlock risk, fire-and-forget unawaited Task)";

    public const string AnalyzeDiRegistration = "Analyze project DI registration completeness, scanning AddSingleton/AddScoped/AddTransient registrations and checking for missing dependencies";

    public const string FindMissingDiRegistrations = "Find constructor dependencies missing DI registration in the project, helping discover service registration omissions";

    public const string DetectMemoryLeaks = "Detect memory leak patterns in the project (unsubscribed events, undisposed IDisposable, static events holding instance references)";

    public const string AddProjectReference = "Add a ProjectReference to the project file";

    public const string AddNuGetPackage = "Add a NuGet package reference (PackageReference) to the project file";

    public const string UpdateProjectProperty = "Update an MSBuild property value in the project file; creates the property if it does not exist, updates it if it does";

    public const string ProjectPathParam = "Project path";

    public const string ProjectFilePathParam = "Project file path (.csproj)";

    public const string ProjectOrSolutionPathParam = "Project or solution path";

    public const string ProjectOrSolutionFileParam = "Project file path (.csproj or .sln)";

    public const string SolutionPathParam = "Solution path";

    public const string SolutionFileParam = "Solution path (.sln or .slnx)";

    public const string TargetProjectFilePathParam = "Target project file path (.csproj)";

    public const string FilePathParam = "File path";

    public const string OptionalFilePathParam = "Optional: specific file diagnostics";

    public const string XamlFilePathParam = "Absolute path of the XAML file";

    public const string AssemblyPathParam = "Assembly file path (.dll or .exe)";

    public const string LineParam = "Line number (0-based)";

    public const string ColumnParam = "Column number (0-based)";

    public const string StartLineParam = "Start line number (0-based)";

    public const string StartColumnParam = "Start column number (0-based)";

    public const string EndLineParam = "End line number (0-based)";

    public const string EndColumnParam = "End column number (0-based)";

    public const string ReferencePathParam = "Referenced project file path";

    public const string TypeNameParam = "Type name";

    public const string MemberNameParam = "Member name";

    public const string ContainingTypeParam = "Containing type name";

    public const string MethodNameParam = "New method name";

    public const string ClassNameParam = "Class name";

    public const string InterfaceNameParam = "Interface name";

    public const string NewNameParam = "New name";

    public const string VariableNameParam = "Variable name (optional, auto-suggest if not provided)";

    public const string FormatParam = "Output format (markdown, html, json)";

    public const string SmellTypeParam = "Optional code smell type filter (e.g., long-method, large-class)";

    public const string MinSeverityParam = "Minimum severity (Minor, Major, Critical)";

    public const string SecurityMinSeverityParam = "Minimum report severity (Critical/High/Medium/Low/Information)";

    public const string IncludeSuggestionsParam = "Whether to include fix suggestions";

    public const string IncludeTrendParam = "Whether to include trend analysis";

    public const string ChangedFilePathParam = "Changed file path";

    public const string ChangeTypeParam = "Change type (MethodSignature, TypeMemberChange, TypeDeletion, etc.)";

    public const string ProjectOrDirectoryParam = "Project file path or directory";

    public const string FileFilterParam = "File filter (e.g., *.cs)";

    public const string GraphFormatParam = "Output format (mermaid, json, dot)";

    public const string MaxNodesParam = "Maximum node count (simplifies if exceeded)";

    public const string HeatmapTypeParam = "Heatmap type (complexity, change-frequency)";

    public const string PeriodDaysParam = "Change frequency lookback days (only effective for change-frequency type)";

    public const string RulesFilePathParam = "Optional custom rule file path; defaults to dotnet-analyzer.rules.json in the project directory";

    public const string OptionalRulesFilePathParam = "Optional custom rule file path";

    public const string OptionalTypeNameFilterParam = "Optional type name filter, only decompile matching types (supports partial matching)";

    public const string AccessibilityParam = "Accessibility filter (Public, Internal, Protected, Private)";

    public const string AllowedLicensesParam = "Allowed license list (comma-separated, empty means all allowed)";

    public const string OptionalSolutionPathParam = "Solution path (optional)";

    public const string StrategyParam = "Optimization strategy: auto (automatic) or aggressive (aggressive cleanup)";

    public const string FileContentParam = "File content";

    public const string SortOrderParam = "Sort order (systemFirst/alphabetical/length)";

    public const string SuggestionsParam = "Suggested import list (optional)";

    public const string FieldsParam = "Field list (type name)";

    public const string BaseCallParam = "Base constructor call (optional)";

    public const string MaxDepthParam = "Maximum depth";

    public const string IncludeIndirectParam = "Whether to include indirect calls";

    public const string DepthParam = "Maximum recursion depth (default 10, 0 = direct calls only)";

    public const string VisualizationFormatParam = "Visualization format (dot, svg, json, mermaid)";

    public const string IgnoreWhitespaceParam = "Whether to ignore whitespace";

    public const string IgnoreCommentsParam = "Whether to ignore comments";

    public const string ContextLinesParam = "Context lines";

    public const string ChangesJsonParam = "Change list (JSON format)";

    public const string FormatCodeParam = "Whether to format the modified code";

    public const string CategoriesParam = "Action category filter (refactor, fix, generate, format)";

    public const string TriggerKindParam = "Trigger type (invoked, triggerCharacter, triggerForIncompleteCompletions)";

    public const string ResolveOverridesParam = "Whether to resolve overrides";

    public const string ResolveAliasesParam = "Whether to resolve aliases";

    public const string IncludeReferencesParam = "Whether to include references";

    public const string IncludeHierarchyParam = "Whether to include hierarchy";

    public const string DocumentFilterParam = "File filter (e.g., *.cs)";

    public const string ApplyChangesParam = "Whether to apply changes (default false, preview only)";

    public const string RenameInCommentsParam = "Whether to rename in comments";

    public const string RenameInStringsParam = "Whether to rename in strings";

    public const string GenerateStubParam = "Generate stub implementation";

    public const string ReportFormatParam = "Report format (markdown, json)";

    public const string PackageIdParam = "NuGet package ID";

    public const string PackageVersionParam = "Package version";

    public const string PropertyNameParam = "MSBuild property name";

    public const string PropertyValueParam = "Property value";

    public const string OptionalRangeParam = "Optional range constraint";

    public const string IncludeTriviaParam = "Whether to include trivia";

    #endregion

    #region Runtime messages

    public static string FileNotFound(string path)
        => string.Format(CultureInfo.InvariantCulture, "File not found: {0}", path);

    public static string PathNotFound(string path)
        => string.Format(CultureInfo.InvariantCulture, "Path not found: {0}", path);

    public static string ParameterRangeInvalid(string param, string min, string max)
        => string.Format(CultureInfo.InvariantCulture, "{0} must be between {1} and {2}", param, min, max);

    public static string ParameterNonNegative(string param)
        => string.Format(CultureInfo.InvariantCulture, "{0} must be greater than or equal to 0", param);

    public static string ParameterRequired(string param)
        => string.Format(CultureInfo.InvariantCulture, "{0} cannot be empty", param);

    public static string FileNotInProject(string path)
        => string.Format(CultureInfo.InvariantCulture, "File not in project: {0}", path);

    public static string FailedToLoadProject(string path)
        => string.Format(CultureInfo.InvariantCulture, "Failed to load project: {0}", path);

    public static string FailedToLoadProjectOrSolution(string path)
        => string.Format(CultureInfo.InvariantCulture, "Failed to load project or solution: {0}", path);

    public static string FailedToGetSyntaxTree(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Failed to get syntax tree: {0}", detail);

    public static string FailedToGetSyntaxTreeGeneric() => "Failed to get syntax tree";

    public static string FailedToGetSemanticModel(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Failed to get semantic model: {0}", detail);

    public static string FailedToGetSemanticModelOrRoot() => "Failed to get semantic model or syntax root";

    public static string SymbolNotFoundAtPosition(string file, string line, string col)
        => string.Format(CultureInfo.InvariantCulture, "Symbol not found at specified position: {0}:{1}:{2}", file, line, col);

    public static string FailedToResolveSymbol() => "Failed to resolve symbol at the specified position";

    public static string ProjectPathRequired() => "Project path cannot be empty";

    public static string FilePathRequired() => "File path cannot be empty";

    public static string LineColumnNonNegative() => "Line and column numbers must be greater than or equal to 0";

    public static string DepthNonNegative() => "Recursion depth must be greater than or equal to 0";

    public static string MaxDepthMinimum() => "Maximum depth must be greater than or equal to 1";

    public static string ContextLinesNonNegative() => "Context lines must be greater than or equal to 0";

    public static string ChangesJsonRequired() => "Change list cannot be empty";

    public static string AssemblyPathRequired() => "Assembly path cannot be empty";

    public static string AssemblyFileMustBeDllOrExe() => "Assembly file must be in .dll or .exe format";

    public static string RuleConfigFileNotFound(string path)
        => string.Format(CultureInfo.InvariantCulture, "Rule configuration file not found: {0}", path);

    public static string ErrorAnalyzingCode(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error analyzing code: {0}", detail);

    public static string ErrorGettingTestCoverage(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting test coverage: {0}", detail);

    public static string ErrorFindingDeadCode(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error finding dead code: {0}", detail);

    public static string ErrorAnalyzingPerformance(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error analyzing performance: {0}", detail);

    public static string ErrorGeneratingDocumentation(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error generating documentation: {0}", detail);

    public static string ErrorFindingReferences(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error finding references: {0}", detail);

    public static string ErrorFindingDeclarations(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error finding declarations: {0}", detail);

    public static string ErrorGettingSymbolInfo(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting symbol info: {0}", detail);

    public static string ErrorGoingToDefinition(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error navigating to definition: {0}", detail);

    public static string ErrorGettingTypeHierarchy(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting type hierarchy: {0}", detail);

    public static string ErrorGettingMemberHierarchy(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting member hierarchy: {0}", detail);

    public static string ErrorGettingSemanticModel(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting semantic model info: {0}", detail);

    public static string ErrorGettingSyntaxTree(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting syntax tree structure: {0}", detail);

    public static string ErrorGettingCodeMetrics(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting code metrics: {0}", detail);

    public static string ErrorExtractingMethod(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error extracting method: {0}", detail);

    public static string ErrorRenamingSymbol(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error renaming symbol: {0}", detail);

    public static string ErrorIntroducingVariable(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error introducing variable: {0}", detail);

    public static string ErrorListingRefactorers(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error listing refactorers: {0}", detail);

    public static string ErrorGeneratingInterfaceImpl(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error generating interface implementation: {0}", detail);

    public static string ErrorGeneratingConstructor(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error generating constructor: {0}", detail);

    public static string ErrorRemovingUnusedUsings(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error removing unused usings: {0}", detail);

    public static string ErrorSortingUsings(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error sorting usings: {0}", detail);

    public static string ErrorAddingMissingImports(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error adding missing usings: {0}", detail);

    public static string ErrorGettingCallerInfo(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting caller info: {0}", detail);

    public static string ErrorGettingCalleeInfo(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting callee info: {0}", detail);

    public static string ErrorGeneratingCallGraph(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error generating call graph: {0}", detail);

    public static string ErrorComparingSyntaxTrees(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error comparing syntax trees: {0}", detail);

    public static string ErrorGettingCodeDiff(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting code diff: {0}", detail);

    public static string ErrorApplyingCodeChange(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error applying code change: {0}", detail);

    public static string ErrorGettingCodeActions(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting code actions: {0}", detail);

    public static string ErrorGettingRefactorings(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting refactorings: {0}", detail);

    public static string ErrorGettingCompletionList(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting completion list: {0}", detail);

    public static string ErrorResolvingSymbol(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error resolving symbol: {0}", detail);

    public static string ErrorGettingDefinitionAndReferences(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting definition and references: {0}", detail);

    public static string ErrorGettingDocumentList(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting document list: {0}", detail);

    public static string ErrorDetectingCodeSmells(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Code smell detection failed: {0}", detail);

    public static string ErrorQuantifyingTechnicalDebt(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Technical debt quantification failed: {0}", detail);

    public static string ErrorGeneratingQualityReport(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Quality report generation failed: {0}", detail);

    public static string ErrorStartingFileWatching(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Failed to start file watching: {0}", detail);

    public static string ErrorStoppingFileWatching(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Failed to stop file watching: {0}", detail);

    public static string ErrorAnalyzingChangeImpact(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Change impact analysis failed: {0}", detail);

    public static string ErrorGettingCacheStatistics(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Failed to get cache statistics: {0}", detail);

    public static string ErrorClearingCache(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Failed to clear cache: {0}", detail);

    public static string ErrorGeneratingDependencyGraph(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Failed to generate dependency graph: {0}", detail);

    public static string ErrorGeneratingHeatmap(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Failed to generate heatmap: {0}", detail);

    public static string ErrorCheckingArchitectureRules(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error checking architecture rules: {0}", detail);

    public static string ErrorEvaluatingArchitecture(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error evaluating architecture: {0}", detail);

    public static string ErrorGeneratingArchitectureSarif(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error generating SARIF report: {0}", detail);

    public static string ErrorDecompilingAssembly(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error decompiling assembly: {0}", detail);

    public static string DecompileFailed() => "Decompilation failed";

    public static string ErrorAnalyzingIL(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error analyzing IL: {0}", detail);

    public static string ErrorGettingAssemblyMetadata(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error reading assembly metadata: {0}", detail);

    public static string ReadMetadataFailed() => "Failed to read metadata";

    public static string ErrorGettingApiSurface(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error extracting API surface: {0}", detail);

    public static string ErrorScanningSecurityVulnerabilities(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error scanning security vulnerabilities: {0}", detail);

    public static string ErrorGeneratingSecuritySarif(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error generating security SARIF report: {0}", detail);

    public static string ErrorCheckingLicenseCompliance(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error checking license compliance: {0}", detail);

    public static string ErrorScanningNuGetVulnerabilities(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error scanning NuGet vulnerabilities: {0}", detail);

    public static string ErrorScanningDependenciesHealth(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error scanning dependency health: {0}", detail);

    public static string ErrorDetectingDependencyConflicts(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error detecting dependency conflicts: {0}", detail);

    public static string ErrorAnalyzingSolutionPerformance(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error analyzing solution performance: {0}", detail);

    public static string ErrorOptimizingWorkspaceCache(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error optimizing workspace cache: {0}", detail);

    public static string ErrorGettingWorkspaceStats(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error getting workspace statistics: {0}", detail);

    public static string ErrorAnalyzingXaml(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error parsing XAML file: {0}", detail);

    public static string ErrorValidatingBindings(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error validating XAML bindings: {0}", detail);

    public static string ErrorAnalyzingXamlResources(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error analyzing XAML resources: {0}", detail);

    public static string ErrorMappingViewViewModel(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error mapping View-ViewModel: {0}", detail);

    public static string ErrorDetectingMvvmViolations(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error detecting MVVM violations: {0}", detail);

    public static string ErrorDetectingAsyncAntipatterns(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error detecting async anti-patterns: {0}", detail);

    public static string ErrorAnalyzingDiRegistration(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error analyzing DI registration: {0}", detail);

    public static string ErrorFindingMissingDiRegistrations(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error finding missing DI registrations: {0}", detail);

    public static string ErrorDetectingMemoryLeaks(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error detecting memory leaks: {0}", detail);

    public static string ErrorAddingProjectReference(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error adding project reference: {0}", detail);

    public static string ErrorAddingNuGetPackage(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error adding NuGet package: {0}", detail);

    public static string ErrorUpdatingProjectProperty(string detail)
        => string.Format(CultureInfo.InvariantCulture, "Error updating project property: {0}", detail);

    public static string AlreadyWatching(string path)
        => string.Format(CultureInfo.InvariantCulture, "Already watching path: {0}", path);

    public static string StartedWatching(string path)
        => string.Format(CultureInfo.InvariantCulture, "Started watching path: {0}", path);

    public static string NotWatching(string path)
        => string.Format(CultureInfo.InvariantCulture, "Not watching path: {0}", path);

    public static string StoppedWatching(string path)
        => string.Format(CultureInfo.InvariantCulture, "Stopped watching path: {0}", path);

    public static string CacheCleared() => "Cache cleared";

    public static string RefactoringCompleted() => "Refactoring completed";

    public static string CoverageVerifiedSummary() => "Coverage data from coverage.cobertura.xml; results can be treated as stable behavior.";

    public static string CoverageHeuristicSummary() => "Current coverage results are based on test file naming and heuristic estimation; they do not equate to real coverage collection results.";

    public static string CoverageHeuristicRemediation() => "Run 'dotnet test --collect:\"XPlat Code Coverage\"' to generate a coverage file and obtain real data.";

    public static string CalleeVerifiedSummary() => "Cross-document callee analysis based on real semantic model, supporting interface/virtual dispatch.";

    public static string ChangeImpactHeuristicSummary() => "Current impact analysis only covers direct public symbol references; it does not include full transitive dependencies and precise test mapping.";

    public static string ChangeImpactHeuristicRemediation() => "Dependency graph and test reference analysis need to be added to upgrade to stable results.";

    public static string HeatmapComplexitySummary() => "Complexity heatmap generated based on real code smell analysis.";

    public static string HeatmapChangeFrequencySummary() => "Change frequency heatmap generated based on real Git history records.";

    public static string SourceCodeTruncated() => "... [truncated, source code too long] ...";

    #endregion

}
